### PR TITLE
update to version 2020.7.2

### PR DESCRIPTION
**Pull request by predragnikolic**
Pylance is really fast. :)

One nasty hack I noticed. I needed to have at least one dependency in the package json("is-number": "^7.0.0") to prevent the LSP-pylace plugin from reinstalling the server each time I open sublime.

That is because of this line. https://github.com/sublimelsp/lsp_utils/blob/af3ee66115a231cc4b4d49610f9d176bc3edbad8/st3/lsp_utils/server_npm_resource.py#L99

If a LSP-* plugin don't have node_modules dependencies, we will forever try to install dependencies... which is the case for LSP-pylance
```

    def _install_dependencies(self, cache_server_path):
        dependencies_installed = os.path.isdir(os.path.join(cache_server_path, 'node_modules'))

        if dependencies_installed:
            self._is_ready = True
            return

        # this will be called only when the plugin gets:
        # - installed for the first time,
        # - or when updated on package control
        install_message = '{}: Installing server'.format(self._package_name)
        log_and_show_message(install_message, show_in_status=False)
``` 

For now I think I will just leave is-number as a "dependency" although totally necessary.

### CODE REVIEW

**Comment by jfcherng** [comment]
> One nasty hack I noticed. I needed to have at least one dependency in the package json("is-number": "^7.0.0") to prevent the LSP-pylace plugin from reinstalling the server each time I open sublime.

Yes, that's a workaround I figured out. Eventually I would expect someone publishes pylance on NPM but the [LICENSE](https://marketplace.visualstudio.com/items/ms-python.vscode-pylance/license) of pylance on the VSCode marketplace seems to remain as the same.

>> INSTALLATION AND USE RIGHTS. a) General. You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. b) Third Party Components. The software may include third party components with separate legal notices or governed by other agreements, as may be described in the ThirdPartyNotices file(s) accompanying the software.

General. You may install and use any number of copies of the software **ONLY** with...

They seem to only change the [LICENSE](https://github.com/microsoft/pylance-release/blob/master/LICENSE) of the issue tracker, which people don't really care.

**Comment by jfcherng** [comment]
And btw, they have released `2020.7.3`.

**Comment by jfcherng** [comment]
The only difference between pylance and pyright seems to be the `onnxruntime` (machine learning related thing). But I don't actually know what it does or whether it actually works outside VSCode.

Someone has published [pyright on NPM](https://www.npmjs.com/package/pyright). So it would be super easy to make LSP-pyright and update it. Pylance is now bloated with `onnxruntime` (for 3 platforms).

**Comment by jfcherng** [comment]
So LSP-pyright is [here](https://github.com/sublimelsp/LSP-pyright). LSP-pylance is actually **[illegal](https://github.com/sublimelsp/LSP-pyright/pull/1#issuecomment-666578504)** at this moment...

**Comment by jfcherng** [comment]
I've made this plugin no longer depend on the NPM resource handler and will auto download Pylance from the market.

**Comment by predragnikolic** [comment]
Thanks for the info.
I don't know what the advantage is of using pylance over pyright. (you mentioned machine learning, but machine learning always seems like a black box to me), so I'll stick with pyls(or pyright) for now.

**Comment by jfcherng** [comment]
I actually don't know either at this moment lol.

**Pull request merged**
